### ISSUE TITLE
First milestone for structuring delivered data

### ISSUE THREAD

**Issue by hassanfa** [Biolymph/minerva#2]
- [x] TSV or SQLite alternative if possible for each patient containing the following:

```
├── 2021-28499-03
│   ├── tumor.merged.cram
│   └── tumor.merged.cram.crai
├── 2022-03973-04
│   ├── normal.merged.cram
│   └── normal.merged.cram.crai
├── SNV.germline.normal.dnascope.vcf.gz
├── SNV.germline.normal.dnascope.vcf.gz.tbi

Filetype table: TSV

patient_id sample_id file_name file_type size md5 file_location index_file index_file_size index_file_md5 hts_file
F005780 2021-28499-03 tumor.merged.cram cram 1111GB m23hdx33333 NA tumor.merged.cram.crai 1GB mm33123771273 NA
F005780 F005780 SNV.germline.normal.dnascope.vcf.gz vcf.gz 11GB h37346 NA

Filecontent table: TSV

patient_id file_name file_type feature_count feature_type
F005780 SNV.germline.normal.dnascope.vcf.gz vcf.gz 77288 variant
F005780 tumor.merged.cram cram 345000000 reads/paired_reads
```

- Expected outcome:
`python file_organizer.py --path ....` and output should the `Filetype table` above.

```bash
htsfile SNV.germline.normal.dnascope.vcf.gz
SNV.germline.normal.dnascope.vcf.gz:	VCF version 4.2 BGZF-compressed variant calling data
```
Above command will tell us file type that we can store in the `Filetype table` produced in the first task.

- [x] Versioning and changelog: Versioning should be via creating a  `__version__.py` and every PR should have the version number bumped. And we will follow https://semver.org/ convention And for changelog we update a file every PR following convention from https://keepachangelog.com/en/1.0.0/

Changelog example: File name: `CHANGELOG.md`
```
# Changelog

## [X.X.X](YYYY-MM-DD)

### Added:
* Added new awesome feature

### Fixed:
* fixed path for reading directory...

## [X.X.X](YYYY-MM-DD)

### Removed:
* removed path for reading directory...
```

- [x]  **Important**: Also print out file and directory counts so we can tally what we missed and what we successfully categorized. Essentially a log + summary.
- [ ] Detect file type via using either Samtools (https://github.com/samtools/samtools) or pysamtools (https://pysam.readthedocs.io/en/latest/index.html) via htsfile functionality. Example:

**Comment by rosarioss** [comment]
Comment on this:  Detect file type via using either Samtools (https://github.com/samtools/samtools) or pysamtools (https://pysam.readthedocs.io/en/latest/index.html) via htsfile functionality. 

Was not possible because of deprecated functions. Fow now it uses a dictionary in file constants.py
